version: '3'
services:
  app:
    container_name: tau_ceti_app
    build:
      context: ./services/app_dev
    volumes:
      - ../project:/var/www
    depends_on:
      - db
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - tau_ceti_network
  server:
    container_name: tau_ceti_server
    build:
      context: ./services/server_dev
    volumes:
      - ../project:/var/www
    ports:
      - 8080:8000
    depends_on:
      - app
    networks:
      - tau_ceti_network
  db:
    container_name: tau_ceti_db
    build:
      context: ./services/db
    volumes:
      # MySQLの設定ファイル
      - ./services/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # データの永続化
      - ./strage/db_data/:/var/lib/mysql
      # ダンプデータのマウント用
      - ./strage/dump/:/var/dump/
    environment:
      MYSQL_ROOT_PASSWORD: tau_ceti_pass
    networks:
      - tau_ceti_network
  phpmyadmin:
    container_name: tau_ceti_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - tau_ceti_network

networks:
  tau_ceti_network: